services:
  - name: Blueprint
    type: web
    runtime: node
    region: frankfurt
    buildCommand: npm install
    startCommand: npm start
    repo: https://github.com/ApOxX7/Blueprint.git
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blueprintdb
          property: connectionString

databases:
  - name: blueprintdb
    region: frankfurt
