services:
  - name: Static Site
    type: web
    buildCommand: npm run build
    env:
      - key: DATABASE_URL
        fromDatabase:
          name: databaseblueprint

databases:
  - name: databaseblueprint
    type: postgres
    version: "15"
