services:
  - name: Static Site
    type: web
    buildCommand: npm run build # Commande pour construire votre application, changez-la selon votre projet
    env:
      - key: DATABASE_URL
        fromDatabase:
          name: databaseblueprint # Le nom de votre base de données sur Render

databases:
  - name: databaseblueprint # Remplacez par le nom que vous souhaitez donner à votre base de données
    type: postgres # Remplacez par le type de votre base de données (postgres, mysql, etc.)
    version: "15" # Version de votre base de données
    disk: 10 # Taille du disque en GB
